# Generated by Django 3.0.3 on 2020-07-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200712_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highestbid',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
