# Generated by Django 3.0.3 on 2020-07-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_highestbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='highestbid',
            field=models.IntegerField(),
        ),
    ]
